#!/usr/bin/env bash
# displays Best School 10 times.
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number, In a list format

COUNT=1
while [ $COUNT -lt 101 ]
do
    if [ $((COUNT%15)) = 0 ]
    then
        echo "FizzBuzz"
    elif [ $((COUNT%3)) = 0 ]
    then
        echo "Fizz"
    elif [ $((COUNT%5)) = 0 ]
    then
        echo "Buzz"
    else
        echo "$COUNT"
    fi
    let COUNT+=1
done
